"$schema" = 'https://starship.rs/config-schema.json'


format = """
$os \
$hostname \
$username \
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$conda\
$time\
$line_break\
$character"""

right_format = """$cmd_duration"""


[os]
disabled = false
style = "bold fg:blue"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = ""
style_root = "bold"
format = '[](fg:blue) [$user]($style)'

[hostname]
ssh_only = false
style = ""
format = '[$hostname]($style)'

[directory]
style = "fg:black"
format = "[](fg:blue) [$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"code" = "󰲋 "

[git_branch]
symbol = ""
# style = "fg:yellow"
format = '[[ [$symbol](fg:blue) $branch ](fg:black)]($style)'

[git_status]
# style = "bg:yellow"
format = '[[($all_status$ahead_behind )](fg:black)]($style)'

[nodejs]
symbol = ""
# style = "bg:green"
format = '[[ $symbol( $version) ](fg:black)]($style)'

[c]
symbol = " "
# style = "bg:green"
format = '[[ $symbol( $version) ](fg:black)]($style)'

[rust]
symbol = ""
# style = "bg:green"
format = '[[ $symbol( $version) ](fg:black)]($style)'

[golang]
symbol = ""
# style = "bg:green"
format = '[[ $symbol( $version) ](fg:black)]($style)'

[php]
symbol = ""
# style = "bg:green"
format = '[[ $symbol( $version) ](fg:black)]($style)'

[java]
symbol = " "
# style = "bg:green"
format = '[[ $symbol( $version) ](fg:black)]($style)'

[kotlin]
symbol = ""
# style = "bg:green"
format = '[[ $symbol( $version) ](fg:black)]($style)'

[haskell]
symbol = ""
# style = "bg:green"
format = '[[ $symbol( $version) ](fg:black)]($style)'

[python]
symbol = ""
# style = "bg:green"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:black)]($style)'

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:black)]($style)'

[conda]
symbol = "  "
style = "fg:black"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
# style = "bg:lavender"
format = '[[ [󰥔](fg:blue) $time ](fg:black)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:blue)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = true
format = "[](bold fg:blue) in $duration "
# style = "bg:lavender"
disabled = false
show_notifications = true
min_time_to_notify = 45000
